### ISSUE TITLE
Error: Missing credentials for "PLAIN"

### ISSUE THREAD

**Issue by srzern** [anivanchen/updated-manga#2]
i got this error
``Debugger attached.
Service is online
Running script
Fetch data successful
Filter data successful
Data comparison successfully
Sending data
Error: Missing credentials for "PLAIN"``

**Comment by anivanchen** [comment]
please check that in your code, you use `pass` instead of `password` as shown below

```
const transporter = nodemailer.createTransport({
        service: 'gmail',
        auth: {
            user: constants.loginUser,
            pass: constants.loginPass
        }
});
```

**Comment by srzern** [comment]
I fix that but i get a new error but i think its because of 2-step verification

**Comment by anivanchen** [comment]
could you send over the new error you are receiving?

**Comment by srzern** [comment]
of course
`Sending data

Error: Invalid login: 534-5.7.9 Application-specific password required. Learn more at

534 5.7.9  https://support.google.com/mail/?p=InvalidSecondFactor g10sm82333ejj.44 - gsmtp

    at SMTPConnection._formatError (C:\Users\sezer\Desktop\updated-manga-main\node_modules\nodemailer\lib\smtp-connection\index.js:784:19)

    at SMTPConnection._actionAUTHComplete (C:\Users\sezer\Desktop\updated-manga-main\node_modules\nodemailer\lib\smtp-connection\index.js:1536:34)

    at SMTPConnection.<anonymous> (C:\Users\sezer\Desktop\updated-manga-main\node_modules\nodemailer\lib\smtp-connection\index.js:540:26)

    at SMTPConnection._processResponse (C:\Users\sezer\Desktop\updated-manga-main\node_modules\nodemailer\lib\smtp-connection\index.js:947:20)

    at SMTPConnection._onData (C:\Users\sezer\Desktop\updated-manga-main\node_modules\nodemailer\lib\smtp-connection\index.js:749:14)

    at TLSSocket.SMTPConnection._onSocketData (C:\Users\sezer\Desktop\updated-manga-main\node_modules\nodemailer\lib\smtp-connection\index.js:189:44)

    at TLSSocket.emit (node:events:394:28)

    at addChunk (node:internal/streams/readable:312:12)

    at readableAddChunk (node:internal/streams/readable:287:9)

    at TLSSocket.Readable.push (node:internal/streams/readable:226:10) {
  code: 'EAUTH',

  response: '534-5.7.9 Application-specific password required. Learn more at\n' +

    '534 5.7.9  https://support.google.com/mail/?p=InvalidSecondFactor g10sm82333ejj.44 - gsmtp',
  responseCode: 534,

  command: 'AUTH PLAIN'
}`

**Comment by anivanchen** [comment]
sorry, this application was not written with 2FA in mind. 

you could write your own code on top of the existing code to support 2FA or you can use an alternate email account without 2FA enabled.

**Comment by srzern** [comment]
Thanks, i will use mails without 2FA.  I looked Nodemailer's website but they say 'you can use with “Application Specific” ' anyway that's not necessary.
